### PR TITLE
Trim CovertRawText.py

### PR DESCRIPTION
**Pull request by nikhilCad**
-Did the same old thing you did with other file
-Commented import cv2  as it was not used
-Added os.chdir("../Images") line to change working directory, because when I first run it I got an error
saying file does not exist. How was this working before? Or have I done something wrong?

### CODE REVIEW

**Comment by nikhilCad** [comment]
Just realised I also added my little git automation script in these commits. You can delete it later on

**Comment by Ankit404butfound** [comment]
Regarding the "File doesn't exists" have you saved them in same folder?

**Comment by Ankit404butfound** [comment]
You indeed messed something 😅, Don't worry, I will update it.

**Comment by nikhilCad** [comment]
I just run that script without touching anything else. It tries to fibd Images in the folder that script is saved. The os command takes directory to Images folder and then the images open.

**Comment by nikhilCad** [comment]
Why do I have to 'save them'. I only opened ConvertRawText.py and it didn't work. Do other scripts change anything with the source images?

**Comment by Ankit404butfound** [comment]
No but the image is needed isn't it?

**Pull request closed without merging**
